export const config = {
  DEBUG: true,
  TOWER_WIDTH: 1,
  TOWER_HEIGHT: 1,
  OUTER_TOWER_RANGE: 1.5,
  OUTER_TOWER_HEALTH: 500,
  OUTER_TOWER_ATTACK: 10,
  OUTER_TOWER_ATTACK_SPEED: 1.5,
  INNER_TOWER_RANGE: 1,
  INNER_TOWER_ATTACK: 15,
  INNER_TOWER_ATTACK_SPEED: 1.5,
  INNER_TOWER_HEALTH: 800,
  TICKS_PER_SECOND: 20
};
